11-chp.frontend/plate_slate/2-subscription/lib/plate_slate_web/router.ex
#---
# Excerpted from "Craft GraphQL APIs in Elixir with Absinthe",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/wwgraphql for more book information.
#---
defmodule PlateSlateWeb.Router do
  use PlateSlateWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin_auth do
    plug PlateSlateWeb.AdminAuth
  end


  pipeline :api do
    plug :accepts, ["json"]
    plug PlateSlateWeb.Context
  end

  scope "/admin", PlateSlateWeb do
    pipe_through :browser

    resources "/session", SessionController,
      only: [:new, :create, :delete],
      singleton: true
  end

  scope "/admin", PlateSlateWeb do
    pipe_through [:browser, :admin_auth]

    resources "/items", ItemController
  end

  scope "/" do
    pipe_through :api

    forward "/api", Absinthe.Plug,
      schema: PlateSlateWeb.Schema

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: PlateSlateWeb.Schema,
      socket: PlateSlateWeb.UserSocket
  end

end

11-chp.frontend/plate_slate/2-subscription/lib/plate_slate_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello PlateSlate!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
            <%= if @conn.assigns[:current_user] do %>
            <li><%= link "Logout", to: session_path(@conn, :delete),
              method: :delete,
              class: "btn btn-danger btn-xs" %>
            </li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>